# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33000cc07c9ddcf2a7b019ea2b64a92ce355e185cdd6a6b27d03f0d020fa1d6115a71590266dc5a2fef72058e662ea140a241d2d254eed14db265be9d7b3c70

test:
  secret_key_base: 80bd84c43bba0e2dff3a29f7527121de3319bb80f2b8cfc1241e65f2d1b349bd5024166a6aa8e243db2e27ee86d38e724384be1099c37525e7ffa11093a29c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
